#!/usr/bin/env python

import os

env = Environment(ENV=os.environ, tools=["inkscape"])

src = "example"

png = env.Inkscape(src + "-1.png", src + ".svg")
pdf = env.Inkscape(src + ".pdf", src + ".svg")
wmf = env.Inkscape(src + ".wmf", src + ".svg")
pdf_tex = env.Inkscape(src + "-2.pdf", src + ".svg",
                       INKSCAPEFLAGS="--export-latex")

png2 = env.Inkscape(src + "-2.svg", pdf)
